sudo: false
language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - develop
  - "/\\d+\\.\\d+\\.\\d+?.*/"
php:
- 5.6
- 7.1
env:
  global:
  - GIT_COMMITTER_NAME=travis-ci
  - GIT_COMMITTER_EMAIL=inc@2inc.org
  - GIT_AUTHOR_NAME=travis-ci
  - GIT_AUTHOR_EMAIL=inc@2inc.org
  - WP_VERSION=latest WP_MULTISITE=0
cache:
  directories:
  - node_modules
  - vendor
  - "$HOME/.composer/cache"
install:
- nvm install 6
- npm install -g yarn
- yarn install
- npm rebuild node-sass
- composer install
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- composer test
- bash bin/create-release-branch.sh
before_install:
- openssl aes-256-cbc -K $encrypted_be1b58611344_key -iv $encrypted_be1b58611344_iv -in .travis/github_deploy_key.enc -out .travis/github_deploy_key -d
- mv .travis/github_deploy_key ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
after_success:
- pwd
- ls -al
before_deploy:
- git clone -b release --quiet git@github.com:inc2734/snow-monkey-bbpress-support.git release
- cp package.json gulpfile.js yarn.lock release
- cd release
- yarn install
- yarn run gulp zip
- ls -la snow-monkey-bbpress-support.zip
- export RELEASE_FILE=$(ls snow-monkey-bbpress-support.zip)
deploy:
  provider: releases
  api_key:
    secure: Zw4Laaa/yie6sPlTNviJWoO/AWjec4WGKqpzHee+kXD2W3320CEUyKfWhGigAolR71zQ3WLlLPCuMffjWp44a534lgrY1BIqRK1scIrMzso6TKaG9+W1tq3rjm5ZBjrxoda7O/6wIlSYOsdmDybj5Qq4twIw69EXcGpSKY/r5d5G3cI4e+1g10oix5rgMpqb3gmkcK/V7LSmNa4+dhQ9dxPvUutm2AmIZJpdVIw7z1StIgsfJqiImyfevpwFEoishXCKKjUKnRTTtsRZdSkEmmcousjPUAO+0ElonT2p1kYVJZ1cG52ivYgMabifNrL8nfwSVyQVqVJk4ODD13WyMiA53CSAFE0Omg9v+rTo9km7w3p6tnWyBmnw2dktNWEEQ/2jmdqhPNFoxtTwjisHK7IEghp/FsoC13AsdJvDjbfk1QZn0UezVTAG+Cl4B7YJ2v2QnZ/zMWLwxrvSeJ7ljwZa+XP3kSjhVhGHRIk06NP2SrI0qpG+s65J8xjtfo+3TKbYbUrCsuC0iGNTQ5WBymEOV3aDrsxs63LmqTK9ctt5T6azlPQiNx/zxay5U3gx0P/dHr9HWX8NAthsOxDUDP+l+7O3l/FF1wFfXy24Et7fwyvoL+8Kv0feXRD+8nklH5CGA9aVdfs9sZHAXIgRmh/0Y6P9GwKFZkZWDUQ1H44=
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    tags: true
    repo: inc2734/snow-monkey-bbpress-support
