sudo: false
dist: trusty
language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - develop
  - "/\\d+\\.\\d+\\.\\d+?.*/"
php:
- 7.2
- 7.3
env:
  global:
  - GIT_COMMITTER_NAME=travis-ci
  - GIT_COMMITTER_EMAIL=inc@2inc.org
  - GIT_AUTHOR_NAME=travis-ci
  - GIT_AUTHOR_EMAIL=inc@2inc.org
  - WP_VERSION=latest WP_MULTISITE=0
cache:
  directories:
  - node_modules
  - vendor
  - "$HOME/.composer/cache"
install:
- nvm install 12
- npm install
- composer install
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- bash bin/install-dependencies.sh
script:
- composer test
before_deploy:
- npm rebuild node-sass
- npm run build
- npm run zip
- ls -la snow-monkey-bbpress-support.zip
- export RELEASE_FILE=$(ls snow-monkey-bbpress-support.zip)
deploy:
  provider: releases
  api_key:
    secure: mhJ0E0uBh2jvc5NOWTihByCSXFGiD3Pz8NDCemcQsyrgntM6sZ7MxX0HMDiMBA4XRrh/FLWwBQ35jQg9RSJJUyhnKxsh3Fu7hOJkhaTs7BvCuhjLVPPU1iH9O66Lmhcpl1ke4J8Jw5htAvLWIH98luMOkkOnjwFtdQiQfHJUvecAtA4/2TxtMdpG7/eBcZcjGvv0CnsO4fAThTfpGi9KKnNqbIV1RKEgvZ4NtWMK6GTkUhrR7+AlVmJ34Q+/OR8LPFTAOHxOclCG+n8gg6ZhXwQzUGjHOfoBv9fY/D7G8TUnRm4nu+nqCN0zf3NbVFy8rvXHIhfr33krpSoatupfYKC47FdVROwqx2r01+zJAv3QeN4e2hV/CMi8t4GM0Y5BO75v0ar3/Jh4ZNkEXbc/8c1Tzih41rcmpCRvGrGRmwjo6zd7GGrogBdHQ0jYChZzFsLksCAGDzCgBmr8w21ZQnCV47qArvAH5YOzLZucLkF/WF6W6i2EAedYB8cE5pDeEGUXBhim2HB3qq0hntMNeBri8WV8XNYPqtZtPCbZNiCbi0JJsDeCSVpMHb/q11RUh0gBw/Gu+B8zf36gqtzRMNCyKmOB+uioKSfxX24eOVa70w9ce7s36q/q3Wa7dkAI2zq7qvkdpStcS0qNQHZvDdqBeF6S6D4Do3ljcqwzhRc=
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    tags: true
    php: 7.3
    repo: inc2734/snow-monkey-bbpress-support
